repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=127]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --line-length=127]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==23.9.16]
        args: [--max-line-length=127, --max-complexity=10]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

  - repo: https://github.com/astral-sh/uv
    rev: v0.1.0
    hooks:
      - id: uv-check
        name: Check Python dependencies with uv
        entry: uv pip check
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.json]

  - repo: https://github.com/docker/compose
    rev: v2.23.0
    hooks:
      - id: docker-compose-check
        name: Check Docker Compose files
        entry: docker compose config --quiet
        language: system
        types: [yaml]
        files: docker-compose.*
        pass_filenames: true

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.2.2
    hooks:
      - id: terraform-fmt
        name: terraform-fmt
        description: Format terraform files
        entry: terraform fmt -check -diff -recursive
        language: system
        types: [file]
        files: \.tf$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.87.1
    hooks:
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov

  - repo: https://github.com/gruntwork-io/terratest
    rev: v0.46.4
    hooks:
      - id: terratest_log_parser
        name: terratest_log_parser
        description: Parse and format terratest logs
        files: \.go$
        types: [go]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-go
        args: [markdown, table, --output-file, README.md, .]
        language: go
        types: [terraform]
        files: \.tf$
