version: '3.8'

services:
  # Graphite - Metrics and Monitoring
  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    restart: unless-stopped
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite_data:/opt/graphite/storage/whisper
      - graphite_logs:/var/log
    environment:
      - GRAPHITE_TIME_ZONE=UTC

  # mcp-memory-libsql
  libsql:
    image: libsql/local-server:v0.24.0
    container_name: libsql
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - libsql_data:/var/lib/libsql
    environment:
      - LIBSQL_AUTHENTICATION=none

  # Neo4j for mcp-neo4j-agent-memory
  neo4j:
    image: neo4j:5.18.0
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G

  # CrewAI for agent orchestration
  crewai:
    image: ghcr.io/joaomdmoura/crewai:latest
    container_name: crewai
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY:-}
    volumes:
      - ./crewai:/app/crewai

  # Letta memory system
  letta:
    image: ghcr.io/letta-ai/letta:latest
    container_name: letta
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - LETTA_API_KEY=${LETTA_API_KEY:-}
    volumes:
      - letta_data:/data

  # Falkor database
  falkor:
    image: falkordb/falkordb:edge
    container_name: falkor
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - falkor_data:/data

  # GraphRAG-SDK service
  graphrag:
    image: ghcr.io/graphrag/sdk:latest
    container_name: graphrag
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - GRAPHRAG_API_KEY=${GRAPHRAG_API_KEY:-}
    volumes:
      - ./graphrag_data:/data

  # Llama Stack
  llama-stack:
    image: ghcr.io/llama-index/llama-stack:latest
    container_name: llama-stack
    restart: unless-stopped
    ports:
      - "8003:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./llama_data:/app/data

  # MCP Crawl4AI RAG
  mcp-crawl4ai-rag:
    image: ghcr.io/cbwinslow/mcp-crawl4ai-rag:latest
    container_name: mcp-crawl4ai-rag
    restart: unless-stopped
    ports:
      - "8004:8000"
    environment:
      - CRAWL4AI_API_KEY=${CRAWL4AI_API_KEY:-}
    volumes:
      - ./crawl4ai_data:/data

volumes:
  graphite_data:
  graphite_logs:
  libsql_data:
  neo4j_data:
  neo4j_logs:
  letta_data:
  falkor_data:
