global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
  - job_name: 'localai'
    static_configs:
      - targets: ['localai:8080']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
