http:
  middlewares:
    # Security Headers
    security-headers:
      headers:
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
        accessControlAllowOriginList:
          - "https://opendiscourse.net"
          - "https://*.opendiscourse.net"
        accessControlMaxAge: 100
        accessControlAllowCredentials: true

    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: "1m"

    # JWT Authentication
    jwt-auth:
      forwardAuth:
        address: "https://supabase.opendiscourse.net/auth/v1/verify"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: false
        authResponseHeaders:
          - "X-User-Id"
          - "X-User-Email"

    # IP Whitelist for Cloudflare
    cloudflare-ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "173.245.48.0/20"
          - "103.21.244.0/22"
          - "103.22.200.0/22"
          - "103.31.4.0/22"
          - "141.101.64.0/18"
          - "108.162.192.0/18"
          - "190.93.240.0/20"
          - "188.114.96.0/20"
          - "197.234.240.0/22"
          - "198.41.128.0/17"
          - "162.158.0.0/15"
          - "104.16.0.0/13"
          - "104.24.0.0/14"
          - "172.64.0.0/13"
          - "131.0.72.0/22"

    # Real IP (for Cloudflare)
    real-ip:
      headers:
        customRequestHeaders:
          X-Real-IP: "{http.request.header.CF-Connecting-IP}"
