provider: aws
access_key: ${AWS_ACCESS_KEY_ID}
secret_key: ${AWS_SECRET_ACCESS_KEY}
region: us-east-1
service: s3
bucket: legislative-datasets
endpoint: https://s3.amazonaws.com
fallback: local_file
enabled: false