name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Update docs
        run: |
          sed -i 's/version: .*/version: ${{ github.ref_name }}/' docs/version.md
          git add docs/version.md
          git commit -m "Update version to ${{ github.ref_name }}"
          git push