---
- name: Install Prometheus for Monitoring
  block:
    - name: Add Prometheus repo
      apt_repository:
        repo: deb https://packagecloud.io/prometheus/prometheus/debian/ bookworm main
        state: present
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes
    - name: Configure Prometheus
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify: restart prometheus
    - name: Start Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes
    - name: Open Prometheus port
      ufw:
        rule: allow
        port: 9090
        proto: tcp
  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted