global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker-host:9323']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'opensearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['opensearch:9200']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # Adjust based on your FastAPI service name

rule_files:
  - 'alert.rules'
