name: 'Backup Secrets'
description: 'Encrypt .env to GH Secrets'
runs:
  using: 'composite'
  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - run: |
        gpg --symmetric --cipher-algo AES256 .env
        gh secret set ENCRYPTED_ENV --body encrypted.env --repo ${{ github.repository }} --token ${{ steps.app-token.outputs.token }}
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}