apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: local-ai-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: frontend-secrets