---
- name: Download Apache Spark
  get_url:
    url: https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
    dest: /tmp/spark-3.5.0-bin-hadoop3.tgz
  become: true

- name: Extract Spark
  unarchive:
    src: /tmp/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt
    remote_src: yes
    owner: spark
    group: spark
  become: true

- name: Set Spark env
  lineinfile:
    path: /opt/spark-3.5.0-bin-hadoop3/conf/spark-env.sh
    line: "export SPARK_HOME=/opt/spark-3.5.0-bin-hadoop3"
    create: yes
  become: true

- name: Create Spark user
  user:
    name: spark
    groups: spark
    shell: /bin/bash
    create_home: yes
  become: true