name: Legacy CI/CD (Backup)

# This workflow is kept for reference but disabled to avoid conflicts
# The main CI/CD is now handled by ci.yml

on:
  workflow_dispatch:  # Only manual trigger
    inputs:
      run_legacy:
        description: 'Run legacy CI/CD workflow'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  PYTHON_VERSION: '3.10'

jobs:
  legacy-workflow:
    name: Legacy Workflow (Disabled)
    runs-on: ubuntu-latest
    if: github.event.inputs.run_legacy == 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Legacy workflow notification
        run: |
          echo "⚠️ This is the legacy CI/CD workflow"
          echo "The main CI/CD pipeline is now in ci.yml"
          echo "This workflow is kept for reference only"
          echo "To use modern CI/CD, check the ci.yml workflow"
