name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity.'
          close-issue-message: 'Closing this issue after prolonged inactivity.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity.'
          close-pr-message: 'Closing this pull request after prolonged inactivity.'
