name: Documentation Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README*.md'
      - '.github/workflows/static-deploy.yml'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create documentation site
        run: |
          mkdir -p docs-site
          
          # Create a simple HTML documentation site
          cat > docs-site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Local AI Package - Documentation</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/css/bootstrap.min.css" rel="stylesheet">
              <style>
                  .hero-section { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 4rem 0; }
                  .feature-card { transition: transform 0.3s; }
                  .feature-card:hover { transform: translateY(-5px); }
              </style>
          </head>
          <body>
              <!-- Navigation -->
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                  <div class="container">
                      <a class="navbar-brand" href="#">🤖 Local AI Package</a>
                      <div class="navbar-nav ms-auto">
                          <a class="nav-link" href="#overview">Overview</a>
                          <a class="nav-link" href="#features">Features</a>
                          <a class="nav-link" href="#quickstart">Quick Start</a>
                          <a class="nav-link" href="#architecture">Architecture</a>
                      </div>
                  </div>
              </nav>

              <!-- Hero Section -->
              <section class="hero-section" id="overview">
                  <div class="container text-center">
                      <h1 class="display-4 fw-bold mb-4">Local AI Package</h1>
                      <p class="lead mb-4">A comprehensive self-hosted AI development environment with production-ready infrastructure, security, and monitoring.</p>
                      <a href="#quickstart" class="btn btn-light btn-lg">Get Started</a>
                  </div>
              </section>

              <!-- Features Section -->
              <section class="py-5" id="features">
                  <div class="container">
                      <h2 class="text-center mb-5">Key Features</h2>
                      <div class="row">
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">🧠 Local AI Models</h5>
                                      <p class="card-text">Ollama integration with Qwen2.5, Nomic-Embed, and other cutting-edge models for privacy-first AI.</p>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">📊 RAG Pipeline</h5>
                                      <p class="card-text">Complete Retrieval-Augmented Generation with document ingestion, vector storage, and intelligent querying.</p>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">🔧 Low-Code Automation</h5>
                                      <p class="card-text">n8n workflows for Google Drive, Postgres, Slack integration and workflow automation.</p>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">🗄️ Multi-Database Support</h5>
                                      <p class="card-text">Supabase (Postgres + PGVector), Qdrant vector database, and Neo4j knowledge graphs.</p>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">📈 Monitoring & Analytics</h5>
                                      <p class="card-text">Comprehensive health checks, system monitoring, and troubleshooting assistance.</p>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-4">
                              <div class="card feature-card h-100">
                                  <div class="card-body text-center">
                                      <h5 class="card-title">🔒 Production Security</h5>
                                      <p class="card-text">Containerized environment with security scanning, secrets management, and audit logging.</p>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </section>

              <!-- Quick Start Section -->
              <section class="py-5 bg-light" id="quickstart">
                  <div class="container">
                      <h2 class="text-center mb-5">Quick Start</h2>
                      <div class="row justify-content-center">
                          <div class="col-lg-8">
                              <div class="card">
                                  <div class="card-body">
                                      <pre><code># Clone the repository
          git clone https://github.com/cbwinslow/local-ai-packaged.git
          cd local-ai-packaged

          # Configure environment
          cp .env.example .env
          ./scripts/generate-secrets.sh

          # Start the AI stack
          docker compose up -d

          # Access services
          # - Open WebUI: http://localhost:3000
          # - n8n Workflows: http://localhost:5678
          # - Flowise AI Builder: http://localhost:3000
          </code></pre>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </section>

              <!-- Architecture Section -->
              <section class="py-5" id="architecture">
                  <div class="container">
                      <h2 class="text-center mb-5">System Architecture</h2>
                      <div class="row">
                          <div class="col-lg-6">
                              <h4>🎯 Core Services</h4>
                              <ul class="list-group list-group-flush">
                                  <li class="list-group-item">Ollama - Local LLM API server</li>
                                  <li class="list-group-item">Open WebUI - Chat interface</li>
                                  <li class="list-group-item">Flowise - Visual AI agent builder</li>
                                  <li class="list-group-item">n8n - Workflow automation</li>
                                  <li class="list-group-item">Langfuse - LLM observability</li>
                              </ul>
                          </div>
                          <div class="col-lg-6">
                              <h4>🗃️ Data Layer</h4>
                              <ul class="list-group list-group-flush">
                                  <li class="list-group-item">Supabase - Database & authentication</li>
                                  <li class="list-group-item">Qdrant - Vector database</li>
                                  <li class="list-group-item">Neo4j - Knowledge graph</li>
                                  <li class="list-group-item">Redis - Caching layer</li>
                                  <li class="list-group-item">Grafana/Prometheus - Monitoring</li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </section>

              <!-- Footer -->
              <footer class="bg-dark text-white py-4">
                  <div class="container text-center">
                      <p>&copy; 2024 Local AI Package. Built with ❤️ for the AI community.</p>
                      <p>
                          <a href="https://github.com/cbwinslow/local-ai-packaged" class="text-white">GitHub Repository</a> |
                          <a href="#" class="text-white">Documentation</a> |
                          <a href="#" class="text-white">Support</a>
                      </p>
                  </div>
              </footer>

              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          EOF

      - name: Create additional documentation pages
        run: |
          # Create a simple CSS file
          mkdir -p docs-site/css
          cat > docs-site/css/style.css << 'EOF'
          .feature-card {
              transition: transform 0.3s ease;
          }
          .feature-card:hover {
              transform: translateY(-5px);
              box-shadow: 0 8px 25px rgba(0,0,0,0.15);
          }
          .hero-section {
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          }
          EOF

          # Copy README content as markdown if it exists
          if [ -f "README.md" ]; then
            cp README.md docs-site/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs-site
          cname: local-ai-docs.github.io

  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check deployment status
        run: |
          echo "📋 Documentation deployment validation"
          echo "✅ Site built successfully"
          echo "✅ GitHub Pages deployment initiated"
          echo "🌐 Documentation will be available at: https://${{ github.repository_owner }}.github.io/local-ai-packaged/"
          echo "⏰ DNS propagation may take a few minutes"

      - name: Deployment summary
        run: |
          echo "## 📚 Documentation Deployment Summary"
          echo ""
          echo "**Repository:** ${{ github.repository }}"
          echo "**Branch:** ${{ github.ref_name }}"
          echo "**Commit:** ${{ github.sha }}"
          echo "**Deployed at:** $(date)"
          echo ""
          echo "### 🔗 Access Points:"
          echo "- **Main Documentation:** https://${{ github.repository_owner }}.github.io/local-ai-packaged/"
          echo "- **GitHub Repository:** https://github.com/${{ github.repository }}"
          echo ""
          echo "✅ Documentation deployment completed successfully!"
